import type { Locale } from './i18n';

const ru = {
  directory: 'Площадки', profile: 'Профиль площадки', title: 'Площадка в цифрах',
  subtitle: 'Как площадка проявляет себя в поисках Pay3Flow: позиции, направления и отзывы пользователей.',
  search: 'Найти площадку', all: 'Все площадки', p2p: 'P2P', spot: 'Spot', exchanger: 'Обменник',
  integrated: 'Доступна в поиске', catalogOnly: 'В каталоге', identity: 'Информация из каталога',
  official: 'Открыть сайт', findRoutes: 'Найти обмен', overview: 'Обзор', directions: 'Направления', reviews: 'Отзывы', about: 'О площадке',
  period: 'Период статистики', days7: '7 дней', days30: '30 дней', days90: '90 дней',
  top10: 'Попадания в топ-10', top1: 'На первом месте', searches: 'Участие в поисках', opens: 'Переходы на сайт',
  top10hint: 'Доля поисков, где хотя бы один маршрут площадки вошёл в первые 10 результатов.',
  top1hint: 'Поиски, где маршрут площадки занял первое место.', searchHint: 'Завершённые поиски с ответом или маршрутом этой площадки.',
  opensHint: 'Открытия сервиса из маршрутов Pay3Flow. Это не число завершённых обменов.',
  ranking: 'Позиции в поиске', rankingSubtitle: 'Как часто маршруты площадки оказываются среди лучших',
  singleDayHint: 'Пока есть данные за один день. Динамика появится по мере накопления истории.',
  share: 'Доля поисков', inTop10: 'В топ-10', inTop1: 'На первом месте',
  performance: 'Результаты за период', performanceSubtitle: 'По завершённым поискам Pay3Flow', averageRank: 'Средняя лучшая позиция',
  response: 'Успешных ответов', speed: 'Средний ответ источника', seconds: 'с', noValue: 'Нет данных',
  popular: 'Популярные направления', popularSubtitle: 'Где пользователи чаще встречают эту площадку', direction: 'Направление',
  participation: 'Поисков', bestRank: 'Лучшая позиция', exchange: 'Обменять',
  reviewsSubtitle: 'Отзывы из внешних источников. Оценка рассчитана по собранной выборке.', reviewAll: 'Все', positive: 'Положительные', critical: 'Критические',
  noReviews: 'Пока нет собранных отзывов', noReviewsHint: 'Отзывы появятся, когда источник предоставит доступные записи.',
  reviewsFailed: 'Не удалось загрузить отзывы', reviewRetry: 'Повторить загрузку', original: 'Источник', more: 'Показать ещё',
  noFilterReviews: 'Нет отзывов с такой оценкой', collected: 'отзывов в выборке', rating: 'Оценка пользователей', unrated: 'Без оценки',
  emptyTitle: 'Статистика ещё собирается', emptyHint: 'После первых завершённых поисков здесь появятся реальные позиции и динамика площадки.',
  failedTitle: 'Статистика временно недоступна', failedHint: 'Не удалось получить данные. Попробуйте загрузить их снова.', retry: 'Повторить', loading: 'Загружаем статистику…',
  noDirections: 'Направления появятся после первых поисков', availableTypes: 'Доступно в Pay3Flow', currencies: 'Валюты из каталога',
  allCurrencies: 'Полный список — в поиске обмена', paymentMethods: 'Способы оплаты', noPaymentMethods: 'Зависят от выбранного направления',
  fees: 'Комиссии', feeHint: 'Условия и комиссии зависят от маршрута. Актуальная сумма отображается в результатах поиска.', feeDocs: 'Условия комиссии',
  methodology: 'Как мы считаем', methodologyText: 'Учитываем только завершённые поиски, запущенные пользователем. Каждый поиск учитывается один раз для каждой участвовавшей площадки. Автообновления и незавершённые поиски исключены. Позиция — в итоговом списке показанных маршрутов.',
  methodologyRank: 'Средняя позиция считается только по поискам, в которых у площадки был показанный маршрут. Дни без поисков не соединяются на графике.',
  timezone: 'Даты и границы периода — UTC.', since: 'Наблюдаем с', updated: 'Обновлено',
  shareProfile: 'Поделиться профилем', copied: 'Ссылка скопирована', copyFailed: 'Скопируйте адрес страницы из браузера',
  directoryTitle: 'Выберите площадку', directorySubtitle: 'Биржи и обменники в одном каталоге. Откройте профиль, чтобы увидеть статистику и отзывы.',
  noVenues: 'Площадки не найдены', clear: 'Сбросить фильтры', viewProfile: 'Открыть профиль',
  catalogFailed: 'Каталог временно недоступен. Показаны сохранённые названия площадок.', unavailable: 'Площадка не найдена в текущем каталоге',
  back: 'К площадкам', reviewLoading: 'Загружаем отзывы…', readMore: 'Читать полностью', showLess: 'Свернуть',
  aboutText: 'Профиль объединяет информацию о площадке и её участии в маршрутах Pay3Flow. Сравнивайте доступные направления, изучайте динамику позиций и отзывы перед выбором обмена.',
};
type Copy = typeof ru;
const en: Copy = {
  directory: 'Platforms', profile: 'Platform profile', title: 'A platform in numbers',
  subtitle: 'How this platform performs in Pay3Flow searches: rankings, directions and customer reviews.',
  search: 'Find a platform', all: 'All platforms', p2p: 'P2P', spot: 'Spot', exchanger: 'Exchanger',
  integrated: 'Available in search', catalogOnly: 'In the directory', identity: 'Directory information',
  official: 'Open website', findRoutes: 'Find an exchange', overview: 'Overview', directions: 'Directions', reviews: 'Reviews', about: 'About',
  period: 'Statistics period', days7: '7 days', days30: '30 days', days90: '90 days',
  top10: 'Top-10 appearances', top1: 'Ranked first', searches: 'Search participation', opens: 'Website opens',
  top10hint: 'Share of searches where at least one route from this platform made the first 10 results.',
  top1hint: 'Searches where a route from this platform ranked first.', searchHint: 'Completed searches with a response or route from this platform.',
  opensHint: 'Service opens from Pay3Flow routes. This does not count completed exchanges.',
  ranking: 'Search rankings', rankingSubtitle: 'How often this platform’s routes appear among the best',
  singleDayHint: 'One day of data so far. Trends will appear as the history grows.',
  share: 'Share of searches', inTop10: 'In the top 10', inTop1: 'Ranked first',
  performance: 'Period performance', performanceSubtitle: 'Based on completed Pay3Flow searches', averageRank: 'Average best rank',
  response: 'Successful responses', speed: 'Average source response', seconds: 's', noValue: 'No data',
  popular: 'Popular directions', popularSubtitle: 'Where users encounter this platform most often', direction: 'Direction',
  participation: 'Searches', bestRank: 'Best rank', exchange: 'Exchange',
  reviewsSubtitle: 'Reviews from external sources. Ratings are calculated from the collected sample.', reviewAll: 'All', positive: 'Positive', critical: 'Critical',
  noReviews: 'No collected reviews yet', noReviewsHint: 'Reviews will appear when the source provides available entries.',
  reviewsFailed: 'Could not load reviews', reviewRetry: 'Try loading again', original: 'Source', more: 'Show more',
  noFilterReviews: 'No reviews with this rating', collected: 'reviews in the sample', rating: 'Customer rating', unrated: 'Unrated',
  emptyTitle: 'Statistics are still being collected', emptyHint: 'Real rankings and trends will appear here after the first completed searches.',
  failedTitle: 'Statistics are temporarily unavailable', failedHint: 'Could not retrieve the data. Try loading it again.', retry: 'Try again', loading: 'Loading statistics…',
  noDirections: 'Directions will appear after the first searches', availableTypes: 'Available in Pay3Flow', currencies: 'Directory currencies',
  allCurrencies: 'See the full list in exchange search', paymentMethods: 'Payment methods', noPaymentMethods: 'Depend on the selected direction',
  fees: 'Fees', feeHint: 'Terms and fees depend on the route. The current amount is shown in search results.', feeDocs: 'Fee terms',
  methodology: 'How we calculate', methodologyText: 'Only completed searches initiated by a user are counted. Each search is counted once per participating platform. Auto-refreshes and unfinished searches are excluded. Rank refers to the final list of displayed routes.',
  methodologyRank: 'Average rank includes only searches with a displayed route from this platform. Days without searches are not connected on the chart.',
  timezone: 'Dates and period boundaries use UTC.', since: 'Observed since', updated: 'Updated',
  shareProfile: 'Share profile', copied: 'Link copied', copyFailed: 'Copy the page address from your browser',
  directoryTitle: 'Choose a platform', directorySubtitle: 'Exchanges and exchangers in one directory. Open a profile to explore statistics and reviews.',
  noVenues: 'No platforms found', clear: 'Clear filters', viewProfile: 'Open profile',
  catalogFailed: 'The directory is temporarily unavailable. Saved platform names are shown.', unavailable: 'Platform not found in the current directory',
  back: 'Back to platforms', reviewLoading: 'Loading reviews…', readMore: 'Read full review', showLess: 'Show less',
  aboutText: 'This profile brings together platform information and its participation in Pay3Flow routes. Compare directions, explore ranking trends and read reviews before choosing an exchange.',
};
// Existing language selector supports Armenian; English remains a complete
// fallback for profile strings that have not been translated yet.
export function profileCopy(locale: Locale): Copy { return locale === 'ru' ? ru : en; }
