<svelte:head><title>OTC exception runbook · Pay3flow</title></svelte:head>
<main>
  <h1>OTC exception runbook</h1><p>Detect → contain → assign → diagnose → reconcile → verify → resolve. The configured incident owner leads the timeline; engineering owns technical recovery and the desk owns payout or refund decisions.</p>
  <section id="federation"><h2>Federation and unknown booking</h2><p>Check the exact Proposal, Intent, OfferAgreement and decision IDs, author, audience, relay cursor and persisted outbox. Query the original desk decision. Retry the same body and ID with a fresh transport signature. An unresolved booking blocks another selection.</p></section>
  <section id="observer"><h2>Observer health</h2><p>Pause new bookings on the affected route. Compare the two configured independent RPCs, network identity, canonical receipts, last complete scan and checkpoint. Rescan from the reconciled checkpoint. Missing telemetry is unhealthy; retain the booked finality policy. Monitoring must remain covered while funds are outstanding.</p></section>
  <section id="payment"><h2>Payment review</h2><p>Compare network, native or token identity, sender, recipient, exact net amount and receiving-chain inclusion time. Ethereum requires the issuer USDT Transfer log and canonical receipt. EVER requires the receiving message trace, successful phases and absence of a bounce. Timely inclusion preserves accepted terms while confirming. Late and mismatched receipts remain in review. Do not request another payment while its original result is unknown.</p></section>
  <section id="payout"><h2>Unknown payout or refund</h2><p>Use the saved handoff, nonce or message, checkpoint and original reference. Another payout or refund remains blocked until the original is conclusively resolved. A canonically finalized failure permits an evidence-backed retry. A wallet prompt error alone proves no chain outcome. Refund only to the booked wallet whose ownership was verified.</p></section>
  <section id="integrity"><h2>P0 integrity incident</h2><p>Pause new bookings and application signing immediately; preserve read-only observation, evidence and audit records. The app cannot freeze external desk wallets. Reconcile every affected obligation. Record verified service restoration before enabling signing, and financial resolution before closing the incident.</p></section>
  <section id="fees"><h2>Fee mismatch</h2><p>Stop new quotes using the faulty policy. Compare the immutable USDT basis, rate, 5 USDT floor, single upward precision rounding, verified completion and unique ledger entry. Preserve customer amounts. Use authorized compensating entries; keep accrued, collected and unpaid fees separate.</p></section>
  <section><h2>Communication and closure</h2><p>P0 acknowledgement: 5 minutes. P1: 15 minutes. P2: 4 staffed hours. Escalate to the configured backup. Send participants a private update at least every 30 minutes while funds are affected. Record owner, evidence, actions, next action and update time. Service restoration cannot close a financially unresolved case. P0/P1 require a root-cause note, preventive test, owner and follow-up date within two business days of resolution.</p></section>
</main>
<style>main { max-width: 800px; margin: 40px auto; padding: 24px; color: var(--color-text); }h1 { font-size: 30px; margin-bottom: 20px; }h2 { font-size: 20px; margin: 30px 0 10px; }p { line-height: 1.7; color: var(--color-text-soft); }section { scroll-margin-top: 90px; }</style>
