use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    if let Err(error) = generate_provider_registry() {
        panic!("failed to build provider registry: {error}");
    }
}

fn generate_provider_registry() -> Result<(), Box<dyn std::error::Error>> {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR")?);
    let providers_dir = manifest_dir.join("providers");
    let registry_path = providers_dir.join("reg.json");
    let registry_text = fs::read_to_string(&registry_path)?;
    let registry = parse_registry(&registry_text)?;

    if registry.is_empty() {
        return Err("providers/reg.json must contain at least one provider".into());
    }

    let mut generated = String::from("// @generated by backend/build.rs; do not edit\n".to_owned());
    generated.push_str(&format!(
        "pub const REGISTRY_JSON: &str = include_str!({:?});\n",
        registry_path.to_string_lossy().to_string()
    ));
    generated.push_str("pub const CONFIGS: &[(&str, &str)] = &[\n");

    for (name, relative_path) in registry {
        let config_path = resolve_config_path(&providers_dir, &relative_path)?;
        let config_text = fs::read_to_string(&config_path)?;
        if config_text.trim().is_empty() {
            return Err(format!("provider config {relative_path} is empty").into());
        }
        if !config_text.contains("\"name\"") || !config_text.contains("\"kind\"") {
            return Err(
                format!("provider config {relative_path} must contain name and kind").into(),
            );
        }

        println!("cargo:rerun-if-changed={}", config_path.display());
        generated.push_str(&format!(
            "    ({:?}, include_str!({:?})),\n",
            name,
            config_path.to_string_lossy().to_string()
        ));
    }
    generated.push_str("];\n");

    println!("cargo:rerun-if-changed={}", registry_path.display());
    let out_dir = PathBuf::from(env::var("OUT_DIR")?);
    fs::write(out_dir.join("providers.rs"), generated)?;
    Ok(())
}

fn parse_registry(text: &str) -> Result<BTreeMap<String, String>, Box<dyn std::error::Error>> {
    let mut registry = BTreeMap::new();
    for line in text.lines() {
        let line = line.trim().trim_end_matches(',').trim();
        if line.is_empty() || line == "{" || line == "}" {
            continue;
        }
        let (name, path) = line
            .split_once(':')
            .ok_or_else(|| format!("invalid provider registry entry: {line:?}"))?;
        let name = json_string(name.trim())?;
        let path = json_string(path.trim())?;
        if registry.insert(name.clone(), path).is_some() {
            return Err(format!("duplicate provider registry key: {name:?}").into());
        }
    }
    Ok(registry)
}

fn json_string(value: &str) -> Result<String, Box<dyn std::error::Error>> {
    let value = value
        .strip_prefix('"')
        .and_then(|value| value.strip_suffix('"'))
        .ok_or_else(|| format!("expected JSON string, got {value:?}"))?;
    Ok(value.replace("\\\"", "\"").replace("\\\\", "\\"))
}

fn resolve_config_path(
    providers_dir: &Path,
    relative_path: &str,
) -> Result<PathBuf, Box<dyn std::error::Error>> {
    if !relative_path.starts_with("./") {
        return Err(format!("provider config path must start with ./: {relative_path:?}").into());
    }
    let path = providers_dir.join(&relative_path[2..]);
    let canonical_providers_dir = providers_dir.canonicalize()?;
    let canonical_path = path.canonicalize()?;
    if !canonical_path.starts_with(&canonical_providers_dir) {
        return Err(format!("provider config path escapes providers/: {relative_path:?}").into());
    }
    Ok(canonical_path)
}
