import type { Locale } from "$lib/i18n";
const en = {
  buyPrice: "Buy price", sellPrice: "Sell price", buyVolume: "Buy volume", sellVolume: "Sell volume",
  titleLead: "Trade on ", titleAccent: "your terms.", selectSendAsset: "Select sending asset", selectReceiveAsset: "Select recipient asset", selectSendNetwork: "Select sending network", selectReceiveNetwork: "Select recipient network", chooseSendAsset: "Choose the asset you send", chooseReceiveAsset: "Choose the asset you receive", sendNetwork: "Sending network", receiveNetwork: "Receiving network",
  title: "Trade on your terms.", subtitle: "Your price. Your amount. A direct exchange.", demo: "Demo market", demoNote: "Preview with sample prices. Orders stay in this browser; no funds move.",
  market: "Market", lastPrice: "Last price", change: "24h change", high: "24h high", low: "24h low", volume: "24h volume",
  bridge: "Bridge", chart: "Chart", book: "Orderbook", activity: "Market activity", collapse: "Collapse", expand: "Expand",
  buy: "Buy", sell: "Sell", limit: "Limit", marketOrder: "Market", send: "You send", receive: "You receive", price: "Price", amount: "Amount", total: "Total", spread: "Spread",
  priceHint: "Choose a price from the orderbook or enter your own.", marketHint: "Estimate from the available demo liquidity.", review: "Review order", enterAmount: "Enter an amount", minimum: "Amount is below the market precision.", liquidity: "Not enough demo liquidity for this amount.", tooLarge: "Enter a smaller amount.", estimated: "Estimated", orderValue: "Order value", execution: "Execution", atPrice: "At your price", bestPrice: "Available prices", fees: "Fees", feesValue: "Not configured", expiry: "Expires in", day: "24 hours", orderNote: "A limit order waits for a matching counterparty.", marketNote: "A market order uses the available opposite offers.",
  candles: "Candlesticks", lines: "Price lines", chartRange: "Chart time range", chartDescription: "Demo buy and sell prices with traded volume", chartReset: "Reset chart", zoomIn: "Zoom in", zoomOut: "Zoom out",
  all: "Both sides", bids: "Buy orders", asks: "Sell orders", bookHint: "Select a price to fill the bridge", grouping: "Price grouping",
  trades: "Recent trades", myOrders: "My orders", history: "Order history", time: "Time", side: "Side", status: "Status", action: "Action", cancel: "Cancel", open: "Open", cancelled: "Cancelled", simulated: "Simulated", noOrders: "Your first order starts here.", noOrdersHint: "Set a price in the bridge and try a demo order.", noHistory: "No order history yet.", noHistoryHint: "Cancelled orders and simulated market trades will appear here.", create: "Create an order", reviewTitle: "One last look.", reviewSubtitle: "Review your demo order before adding it.", confirm: "Create demo order", simulate: "Simulate market order", close: "Close", back: "Back", orderCreated: "Demo order added to My orders.", orderSimulated: "Market order simulated. See Order history.", orderCancelled: "Demo order cancelled.", demoOnly: "Demo order · no wallet signature or transfer", filled: "Filled", network: "Settlement asset", direct: "Direct OTC", marketPicker: "Choose market", preview: "OTC preview", available: "Available in the demo", buyPressure: "Buy", sellPressure: "Sell",
};
type Copy = Record<keyof typeof en, string>;
const ru: Copy = {
  buyPrice: "Цена покупки", sellPrice: "Цена продажи", buyVolume: "Объём покупок", sellVolume: "Объём продаж",
  titleLead: "Сделки на ", titleAccent: "ваших условиях.", selectSendAsset: "Выбрать отправляемый актив", selectReceiveAsset: "Выбрать получаемый актив", selectSendNetwork: "Выбрать сеть отправки", selectReceiveNetwork: "Выбрать сеть получения", chooseSendAsset: "Выберите отправляемый актив", chooseReceiveAsset: "Выберите получаемый актив", sendNetwork: "Сеть отправки", receiveNetwork: "Сеть получения",
  title: "Сделки на ваших условиях.", subtitle: "Ваша цена. Ваш объём. Прямой обмен.", demo: "Демо-рынок", demoNote: "Цены для примера. Ордера остаются в этом браузере, средства не переводятся.",
  market: "Рынок", lastPrice: "Последняя цена", change: "Изменение за 24ч", high: "Макс. за 24ч", low: "Мин. за 24ч", volume: "Объём за 24ч",
  bridge: "Bridge", chart: "График", book: "Стакан", activity: "Активность рынка", collapse: "Свернуть", expand: "Развернуть",
  buy: "Купить", sell: "Продать", limit: "Лимитный", marketOrder: "Рыночный", send: "Вы отправляете", receive: "Вы получаете", price: "Цена", amount: "Объём", total: "Всего", spread: "Спред",
  priceHint: "Выберите цену в стакане или укажите свою.", marketHint: "Расчёт по доступным предложениям демо-рынка.", review: "Проверить ордер", enterAmount: "Введите сумму", minimum: "Сумма меньше точности рынка.", liquidity: "Для этой суммы не хватает ликвидности демо-рынка.", tooLarge: "Введите меньшую сумму.", estimated: "Предварительно", orderValue: "Сумма ордера", execution: "Исполнение", atPrice: "По вашей цене", bestPrice: "По доступным ценам", fees: "Комиссия", feesValue: "Не настроена", expiry: "Срок ордера", day: "24 часа", orderNote: "Лимитный ордер ждёт встречного предложения.", marketNote: "Рыночный ордер использует доступные встречные предложения.",
  candles: "Свечи", lines: "Линии цены", chartRange: "Период графика", chartDescription: "Демонстрационный график цен покупки, продажи и объёма", chartReset: "Сбросить график", zoomIn: "Приблизить", zoomOut: "Отдалить",
  all: "Обе стороны", bids: "Покупка", asks: "Продажа", bookHint: "Нажмите на цену — она появится в bridge", grouping: "Группировка цен",
  trades: "Последние сделки", myOrders: "Мои ордера", history: "История ордеров", time: "Время", side: "Сторона", status: "Статус", action: "Действие", cancel: "Отменить", open: "Открыт", cancelled: "Отменён", simulated: "Симуляция", noOrders: "Первый ордер начинается здесь.", noOrdersHint: "Задайте цену в bridge и создайте демо-ордер.", noHistory: "История пока пуста.", noHistoryHint: "Здесь появятся отменённые ордера и симуляции рыночных сделок.", create: "Создать ордер", reviewTitle: "Последняя проверка.", reviewSubtitle: "Проверьте демо-ордер перед созданием.", confirm: "Создать демо-ордер", simulate: "Симулировать рыночный ордер", close: "Закрыть", back: "Назад", orderCreated: "Демо-ордер добавлен в «Мои ордера».", orderSimulated: "Рыночный ордер симулирован. Откройте историю.", orderCancelled: "Демо-ордер отменён.", demoOnly: "Демо-ордер · без подписи кошелька и перевода", filled: "Исполнено", network: "Актив расчёта", direct: "Прямой OTC", marketPicker: "Выбрать рынок", preview: "OTC-превью", available: "Доступно в демо", buyPressure: "Покупка", sellPressure: "Продажа",
};
const hy: Copy = {
  buyPrice: "Գնման գին", sellPrice: "Վաճառքի գին", buyVolume: "Գնումների ծավալ", sellVolume: "Վաճառքների ծավալ",
  titleLead: "Առևտուր՝ ", titleAccent: "ձեր պայմաններով։", title: "Առևտուր՝ ձեր պայմաններով։", subtitle: "Ձեր գինը։ Ձեր ծավալը։ Ուղղակի փոխանակում։",
  selectSendAsset: "Ընտրել ուղարկվող ակտիվը", selectReceiveAsset: "Ընտրել ստացվող ակտիվը", selectSendNetwork: "Ընտրել ուղարկման ցանցը", selectReceiveNetwork: "Ընտրել ստացման ցանցը", chooseSendAsset: "Ընտրեք ուղարկվող ակտիվը", chooseReceiveAsset: "Ընտրեք ստացվող ակտիվը", sendNetwork: "Ուղարկման ցանց", receiveNetwork: "Ստացման ցանց",
  demo: "Փորձնական շուկա", demoNote: "Օրինակային գներ։ Պատվերները պահվում են այս զննարկիչում․ միջոցներ չեն փոխանցվում։",
  market: "Շուկա", lastPrice: "Վերջին գին", change: "Փոփոխություն՝ 24 ժ", high: "Առավելագույնը՝ 24 ժ", low: "Նվազագույնը՝ 24 ժ", volume: "Ծավալը՝ 24 ժ",
  bridge: "Կամուրջ", chart: "Գրաֆիկ", book: "Պատվերների գիրք", activity: "Շուկայի ակտիվություն", collapse: "Ծալել", expand: "Բացել",
  buy: "Գնել", sell: "Վաճառել", limit: "Լիմիտային", marketOrder: "Շուկայական", send: "Դուք ուղարկում եք", receive: "Դուք ստանում եք", price: "Գին", amount: "Քանակ", total: "Ընդամենը", spread: "Գների տարբերություն",
  priceHint: "Ընտրեք գինը պատվերների գրքից կամ մուտքագրեք ձերը։", marketHint: "Հաշվարկ՝ փորձնական շուկայի հասանելի առաջարկներով։", review: "Ստուգել պատվերը", enterAmount: "Մուտքագրեք գումարը", minimum: "Քանակը փոքր է շուկայի թույլատրելի նվազագույնից։", liquidity: "Փորձնական շուկայում այս քանակի համար բավարար առաջարկներ չկան։", tooLarge: "Մուտքագրեք ավելի փոքր գումար։", estimated: "Մոտավոր", orderValue: "Պատվերի արժեք", execution: "Կատարում", atPrice: "Ձեր գնով", bestPrice: "Հասանելի գներով", fees: "Վճարներ", feesValue: "Սահմանված չեն", expiry: "Գործում է", day: "24 ժամ", orderNote: "Լիմիտային պատվերը սպասում է համապատասխան հանդիպակաց առաջարկի։", marketNote: "Շուկայական պատվերն օգտագործում է հասանելի հանդիպակաց առաջարկները։",
  candles: "Մոմեր", lines: "Գների գծեր", chartRange: "Գրաֆիկի ժամանակահատված", chartDescription: "Գնման և վաճառքի գների ու ծավալի փորձնական գրաֆիկ", chartReset: "Վերակայել գրաֆիկը", zoomIn: "Մեծացնել", zoomOut: "Փոքրացնել",
  all: "Երկու կողմը", bids: "Գնման պատվերներ", asks: "Վաճառքի պատվերներ", bookHint: "Ընտրեք գինը՝ կամուրջը լրացնելու համար", grouping: "Գների խմբավորում",
  trades: "Վերջին գործարքներ", myOrders: "Իմ պատվերները", history: "Պատվերների պատմություն", time: "Ժամ", side: "Կողմ", status: "Կարգավիճակ", action: "Գործողություն", cancel: "Չեղարկել", open: "Բաց", cancelled: "Չեղարկված", simulated: "Մոդելավորված", noOrders: "Ձեր առաջին պատվերը սկսվում է այստեղ։", noOrdersHint: "Կամրջում նշեք գինը և ստեղծեք փորձնական պատվեր։", noHistory: "Պատվերների պատմությունը դեռ դատարկ է։", noHistoryHint: "Այստեղ կհայտնվեն չեղարկված պատվերներն ու մոդելավորված շուկայական գործարքները։", create: "Ստեղծել պատվեր", reviewTitle: "Վերջնական ստուգում։", reviewSubtitle: "Ստուգեք փորձնական պատվերը՝ նախքան ստեղծելը։", confirm: "Ստեղծել փորձնական պատվեր", simulate: "Մոդելավորել շուկայական պատվերը", close: "Փակել", back: "Հետ", orderCreated: "Փորձնական պատվերն ավելացվել է «Իմ պատվերները» բաժնում։", orderSimulated: "Շուկայական պատվերը մոդելավորվել է։ Բացեք պատվերների պատմությունը։", orderCancelled: "Փորձնական պատվերը չեղարկվել է։", demoOnly: "Փորձնական պատվեր՝ առանց դրամապանակի ստորագրության կամ փոխանցման", filled: "Կատարված", network: "Հաշվարկի ակտիվ", direct: "Ուղղակի OTC", marketPicker: "Ընտրել շուկան", preview: "OTC նախադիտում", available: "Հասանելի է փորձնական շուկայում", buyPressure: "Գնել", sellPressure: "Վաճառել",
};
export function otcCopy(language: Locale): Copy { return ({ en, ru, hy })[language]; }
