<script lang="ts">
  import { onMount } from 'svelte';
  import Header from '$lib/components/Header.svelte';
  import { fetchProviders } from '$lib/exchange';
  import { profileVenues, venuesFromCatalog, type MarketType } from '$lib/provider-profile';
  import { profileCopy } from '$lib/provider-profile-copy';
  import { locale } from '$lib/i18n';
  import { venueIcon } from '$lib/icons';
  import { SITE_URL } from '$lib/home-content';
  let venues = profileVenues, query = '', filter: MarketType | 'all' = 'all', failed = false;
  $: copy = profileCopy($locale);
  $: filtered = venues.filter(venue => (filter === 'all' || venue.types.includes(filter)) && `${venue.name} ${venue.slug}`.toLowerCase().includes(query.trim().toLowerCase()));
  onMount(() => {
    const controller = new AbortController();
    fetchProviders(AbortSignal.any([controller.signal, AbortSignal.timeout(15000)]))
      .then(catalog => { if (!controller.signal.aborted) venues = venuesFromCatalog(catalog); })
      .catch(() => { if (!controller.signal.aborted) failed = true; });
    return () => controller.abort();
  });
</script>
<svelte:head><title>{copy.directory} — Pay3Flow</title><meta name="description" content={copy.directorySubtitle} /><link rel="canonical" href={`${SITE_URL.replace(/\/$/, '')}/providers`} /></svelte:head>
<div class="appShell"><Header activePage="providers" /><main class="directory"><span class="eyebrow">PAY3FLOW / PLATFORMS</span><h1>{copy.directoryTitle}<span>↗</span></h1><p class="lead">{copy.directorySubtitle}</p><div class="toolbar"><div class="filters" aria-label={copy.availableTypes}>{#each ['all', 'p2p', 'spot', 'exchanger'] as type}<button type="button" class:active={filter === type} aria-pressed={filter === type} on:click={() => filter = type as typeof filter}>{type === 'all' ? copy.all : copy[type as MarketType]}</button>{/each}</div><label class="search"><span aria-hidden="true">⌕</span><input type="search" bind:value={query} placeholder={copy.search} aria-label={copy.search} /></label></div>{#if failed}<p class="notice" role="status">{copy.catalogFailed}</p>{/if}<div class="venueGrid">{#each filtered as venue (venue.slug)}<a class="venueCard" href={`/providers/${venue.slug}`} aria-label={`${copy.viewProfile}: ${venue.name}`}><div class="cardTop"><img src={venueIcon(venue.slug)} alt="" width="48" height="48" /><span>↗</span></div><h2>{venue.name}</h2><div class="types">{#each venue.types as type}<span>{copy[type]}</span>{/each}</div><div class="cardFooter"><span>{copy.viewProfile}</span><span>→</span></div></a>{:else}<div class="empty"><h2>{copy.noVenues}</h2><button type="button" on:click={() => { query = ''; filter = 'all'; }}>{copy.clear} ↻</button></div>{/each}</div></main><footer class="siteFooter"><span>Pay3Flow</span><a href="/">SWAP ↗</a><a href="/terms">{$locale === 'ru' ? 'Условия использования' : 'Usage policy'}</a></footer></div>
<style>
  .directory { width: min(1180px, calc(100% - 2 * var(--page-gutter))); margin: 50px auto; }.eyebrow { color: var(--color-text-soft); font-family: var(--font-mono); font-size: 10px; letter-spacing: .12em; }h1 { display: flex; align-items: center; gap: 16px; font-size: clamp(30px, 4vw, 44px); margin: 16px 0; letter-spacing: -1.5px; }h1 span { color: var(--color-accent-text); }.lead { max-width: 590px; font-size: 13px; line-height: 1.9; color: var(--color-text-soft); }.toolbar { display: flex; justify-content: space-between; align-items: center; gap: 20px; margin: 35px 0 23px; }.filters { display: flex; flex-wrap: wrap; gap: 6px; }.filters button { padding: 10px 16px; border: 1px solid var(--color-border); border-radius: 7px; font-size: 11px; color: var(--color-text-soft); background: var(--color-paper); }.filters button.active { background: var(--color-accent); color: #172110; border-color: var(--color-accent); }.search { display: flex; align-items: center; gap: 10px; padding: 6px 14px; background: var(--color-paper); border: 1px solid var(--color-border); border-radius: 7px; }.search > span { font-size: 24px; color: var(--color-text-soft); }.search input { width: 190px; border: 0; background: transparent; outline: none; font-size: 12px; }.search:focus-within { outline: 2px solid var(--color-focus); outline-offset: 2px; }.venueGrid { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 17px; }.venueCard { display: block; padding: 24px; border: 1px solid var(--color-border); border-radius: 14px; background: var(--color-paper); transition: border-color .18s, transform .18s; }.venueCard:hover { transform: translateY(-3px); border-color: var(--color-accent-text); }.cardTop { display: flex; align-items: flex-start; justify-content: space-between; }.cardTop img { object-fit: contain; border-radius: 12px; }.cardTop > span { color: var(--color-text-soft); }h2 { font-size: 19px; letter-spacing: -.5px; margin: 24px 0 12px; }.types { display: flex; gap: 5px; flex-wrap: wrap; }.types span { padding: 5px 8px; color: var(--color-accent-text); background: var(--color-accent-soft); border-radius: 4px; font-size: 10px; }.cardFooter { display: flex; justify-content: space-between; border-top: 1px solid var(--color-border); padding-top: 16px; margin-top: 25px; font-size: 10px; color: var(--color-text-soft); }.notice { color: var(--color-text-soft); font-size: 11px; margin-bottom: 18px; }.empty { grid-column: 1 / -1; padding: 35px; border: 1px solid var(--color-border); border-radius: 12px; text-align: center; }.empty button { padding: 12px; color: var(--color-accent-text); font-size: 12px; }
  @media (max-width: 1000px) { .venueGrid { grid-template-columns: repeat(3, minmax(0, 1fr)); } }
  @media (max-width: 760px) { .venueGrid { grid-template-columns: repeat(2, minmax(0, 1fr)); }.toolbar { flex-wrap: wrap; gap: 16px; }.search { width: 100%; }.search input { flex: 1; width: 100%; }.directory { margin-top: 28px; } }
  @media (max-width: 420px) { .venueCard { padding: 18px; }.venueGrid { gap: 10px; }h2 { font-size: 16px; }.filters button { padding: 9px 12px; }.cardFooter { font-size: 9px; } }
</style>
