<script lang="ts">
  import { assetIcon, venueIcon } from "$lib/icons";
  import { locale, t } from "$lib/i18n";
  import type { TutorialStep } from "$lib/route-tutorial";
  import type { RouteCandidate } from "$lib/exchange";
  import { cifraTrade } from "./frames";

  // svelte-ignore export_let_unused
  export let route: RouteCandidate;
  export let step: TutorialStep;
  export let frame = 0;
  export let playing = true;
  export let progress = 1;
  $: copy = (key: string) => t(key, {}, $locale);
  $: trade = cifraTrade(step);
  $: amountValue = step.amount?.endsWith(` ${step.from}`) ? step.amount.slice(0, -(step.from.length + 1)) : step.amount;
  $: ticker = trade?.ticker ?? `${step.from} → ${step.to}`;
  $: phase = Math.min(5, frame);
  $: typedTicker = phase === 2 && playing ? ticker.slice(0, Math.max(1, Math.floor(ticker.length * Math.min(1, progress * 2)))) : ticker;
  $: action = copy(trade ? trade.buying ? "Place a buy order" : "Place a sell order" : "Check the trading pair");
  $: positions = [{ x: 72, y: 23 }, { x: 83, y: 11 }, { x: 29, y: 31 }, { x: 81, y: 63 }, { x: 80, y: 86 }, { x: 24, y: 88 }];
  $: target = positions[phase];
  $: previous = positions[Math.max(0, phase - 1)];
  $: motion = Math.min(1, Math.max(0, progress * 2));
  $: cursorX = previous.x + (target.x - previous.x) * motion;
  $: cursorY = previous.y + (target.y - previous.y) * motion;
</script>

<div class="cifraCard" class:paused={!playing} data-testid="cifra-tradernet-card" data-phase={phase} data-side={trade ? trade.buying ? "buy" : "sell" : "unknown"} style={`--cursor-x:${cursorX}%;--cursor-y:${cursorY}%`}>
  <div class="brand"><img src={venueIcon("cifra-broker")} alt="" /><strong>CIFRA <span>markets</span></strong><small>Tradernet</small><span class="topUp" class:highlight={phase === 1}>{copy("Top up")}</span></div>
  <div class="navigation"><span class:chosen={phase === 0}>{copy("Profile")}</span><span class:chosen={phase >= 2 && phase <= 4}>{copy("Trade section")}</span><span class:chosen={phase === 5}>{copy("Portfolio")}</span><span>{copy("Cabinet")}</span></div>
  {#if phase === 0}
    <div class="account panel"><span class="panelTitle">{copy("Account verification")}</span><div class="accountRow"><span>01</span><div><strong>{copy("Sign in or open an account")}</strong><small>tradernet.by</small></div></div><div class="accountRow"><span>02</span><div><strong>{copy("Identity and address")}</strong><small>{copy("Complete verification in your account")}</small></div></div><div class="accountRow"><span>03</span><div><strong>{copy("Crypto withdrawals")}</strong><small>{copy("Advanced verification")}</small></div></div></div>
  {:else if phase === 1}
    <div class="funding panel"><span class="panelTitle">{copy("Top up")}</span><div class="fundingTabs"><span>{copy("Bank details")}</span><span>{copy("Digital currencies")}</span></div><div class="fundingAsset highlight"><img src={assetIcon(step.from)} alt="" /><strong>{step.from}</strong><span>⌄</span></div><div class="fundingDetails"><span>{copy("Sum")}</span><strong>{step.amount ?? copy("Check your source balance")}</strong>{#if step.network}<small>{copy("Network")} · {step.network}</small>{/if}</div><div class="ownDetails">{copy("Use the details from your own account")}</div></div>
  {:else if phase === 5}
    <div class="panel"><span class="panelTitle">{copy("Orders")} · {copy("Portfolio")}</span><div class="history highlight"><span>{copy("Check actual order fills")}</span></div><div class="balance"><img src={assetIcon(step.to)} alt="" /><div><strong>{step.to}</strong><small>{copy("Check the actual balance")}</small></div></div><div class="ownDetails finalDetails">{copy("Withdraw money / crypto")}<br />{copy("Check the receiving details and fees")}</div></div>
  {:else}
    <div class="terminal">
      <div class="quotes"><div class="tickerSearch" class:highlight={phase === 2}><span>⌕</span><strong data-testid="cifra-ticker">{typedTicker}</strong></div><div class="tickerHeading"><span>{copy("Ticker")}</span><span>{copy("Price")}</span></div><div class="tickerRow selected"><img src={assetIcon(trade?.base ?? step.from)} alt="" /><strong>{trade?.base ?? step.from}-{trade?.quote ?? step.to}</strong><span>—</span></div><div class="chart"><svg viewBox="0 0 240 90" preserveAspectRatio="none" fill="none" aria-hidden="true"><path d="M0 70 20 65 34 72 54 42 74 50 91 35 111 46 130 24 155 40 176 18 194 27 214 12 240 20" stroke="#299950" stroke-width="2" /></svg><small>{copy("Illustrative chart")}</small></div><div class="history"><span>{copy("Orders")}</span><span>{copy("Portfolio")}</span></div></div>
      <div class="orderPanel" class:highlight={phase === 3}><strong>{ticker}</strong><div class="orderSide" class:selling={trade && !trade.buying}>{copy(trade ? trade.buying ? "Buy" : "Sell" : "Check the trading pair")}</div><span class="orderLabel">{copy("Market order")}</span><div class="marketType">{copy("At market")} <span>⌄</span></div><div class="amountTabs"><span class:chosen={trade?.buying}>{copy("Sum")}</span><span class:chosen={trade && !trade.buying}>{copy("Order quantity")}</span></div><div class="amountInput" class:highlight={phase === 3} data-testid="cifra-order-amount">{amountValue ?? copy("Your amount")}<small>{trade?.buying ? trade.quote : trade?.base ?? step.from}</small></div><div class="orderTotal"><span>{copy("Order total")}</span><strong>{copy("Check the live quote")}</strong></div><div class="orderAction" class:selling={trade && !trade.buying} class:highlight={phase === 4} class:clicked={phase === 4 && progress >= .6} data-testid="cifra-order-action">{action}</div></div>
    </div>
  {/if}
  <svg class="cursor" viewBox="0 0 32 38" fill="none" aria-hidden="true"><path d="M3 2 27 22 15 24 9 35 3 2Z" fill="#3a9df8" stroke="#fff" stroke-width="2.5" /></svg>
</div>

<style>
  .cifraCard { position: absolute; inset: 24px 30px 116px; container-type: inline-size; max-width: 620px; margin-inline: auto; overflow: hidden; border: 1px solid #d9dee5; border-radius: 12px; background: #f5f6f8; color: #283442; box-shadow: 0 20px 50px var(--scene-shadow); font-size: 11px; }
  .brand { height: 44px; padding: 0 14px; display: flex; align-items: center; gap: 6px; background: #fff; }.brand img { width: 23px; height: 23px; object-fit: contain; border-radius: 5px; }.brand strong { font-size: 15px; letter-spacing: -.05em; }.brand strong span { font-size: 11px; font-weight: 500; letter-spacing: -.02em; }.brand > small { margin-left: auto; color: #8b95a3; font-size: 9px; }.topUp { margin-left: 8px; padding: 6px 8px; border-radius: 4px; background: #23b647; color: #fff; font-size: 9px; }
  .navigation { display: flex; justify-content: center; gap: 22px; height: 32px; background: #fff; border-block: 1px solid #edf0f4; align-items: center; font-size: 9px; color: #7c8592; }.navigation .chosen { color: #233340; border-bottom: 2px solid #24b549; padding-block: 9px; }
  .panel { padding: 16px 20px; }.panelTitle { display: block; font-weight: 700; font-size: 13px; margin-bottom: 15px; }.accountRow { display: flex; align-items: center; gap: 12px; margin-block: 12px; padding: 9px; background: #fff; border-radius: 6px; }.accountRow > span { color: #419cfb; font: 10px var(--font-mono); }.accountRow > div { display: grid; gap: 4px; }.accountRow small { color: #7b8795; font-size: 10px; }
  .fundingTabs { display: flex; gap: 18px; color: #728092; margin-bottom: 13px; font-size: 10px; }.fundingAsset { display: flex; align-items: center; gap: 8px; padding: 9px; background: #fff; border-radius: 5px; }.fundingAsset img { width: 20px; height: 20px; }.fundingAsset > span { margin-left: auto; }.fundingDetails { display: grid; gap: 6px; padding: 12px 0; }.fundingDetails > span, .fundingDetails small { color: #6f7a88; font-size: 10px; }.ownDetails { color: #1f7bad; background: #e8f4fe; padding: 10px; border-radius: 5px; font-size: 10px; }
  .terminal { display: grid; grid-template-columns: minmax(0, 1.1fr) minmax(0, 1fr); gap: 10px; padding: 12px; }.quotes, .orderPanel { min-width: 0; }.tickerSearch { display: flex; gap: 7px; align-items: center; padding: 8px; border: 1px solid #d9e0e8; border-radius: 5px; background: #fff; overflow: hidden; white-space: nowrap; font-size: 10px; }.tickerHeading { display: flex; justify-content: space-between; padding: 9px 5px; font-size: 8px; color: #7c8592; }.tickerRow { display: flex; align-items: center; gap: 5px; padding: 8px 5px; background: #fff; font-size: 9px; }.tickerRow img { width: 15px; height: 15px; }.tickerRow > span { margin-left: auto; }.chart { position: relative; height: 92px; margin-top: 10px; background: linear-gradient(#dce3e944 1px, transparent 1px); background-size: 100% 24px; }.chart svg { width: 100%; height: 100%; }.chart small { position: absolute; left: 4px; bottom: 0; font-size: 7px; color: #7c8592; background: #f5f6f8; }.history { display: flex; gap: 14px; margin-top: 12px; padding: 8px 5px; border-bottom: 1px solid #ced7e0; font-size: 9px; }.balance { display: flex; align-items: center; gap: 6px; margin-top: 10px; }.balance img { width: 20px; height: 20px; }.balance > div { display: grid; gap: 4px; }.balance small { color: #74808c; font-size: 8px; }
  .orderPanel { padding: 9px; border: 1px solid #e1e5eb; background: #fff; border-radius: 6px; }.orderPanel > strong { display: block; font-size: 10px; overflow-wrap: anywhere; }.orderSide { margin-top: 9px; padding: 7px; color: #219545; background: #e6f9e9; text-align: center; font-weight: 700; }.orderSide.selling { color: #d94855; background: #ffebed; }.orderLabel { display: block; font-size: 8px; margin: 10px 0 5px; color: #74808c; }.marketType { display: flex; justify-content: space-between; padding: 6px; border: 1px solid #e1e5eb; border-radius: 4px; font-size: 9px; }.amountTabs { display: flex; gap: 10px; padding-top: 10px; font-size: 8px; color: #8e97a2; }.amountTabs .chosen { color: #2e3946; font-weight: 700; }.amountInput { display: flex; flex-wrap: wrap; gap: 4px; align-items: center; margin-top: 5px; padding: 8px 5px; min-height: 28px; border: 1px solid #e1e5eb; border-radius: 4px; font-size: 10px; overflow-wrap: anywhere; }.amountInput small { margin-left: auto; color: #88929d; font-size: 8px; }.orderTotal { display: grid; gap: 5px; margin-top: 10px; font-size: 8px; color: #74808c; }.orderTotal strong { font-weight: 500; color: #344352; }.orderAction { position: relative; margin-top: 12px; padding: 9px 5px; text-align: center; background: #23b647; color: #fff; border-radius: 4px; font-size: 9px; font-weight: 600; }.orderAction.selling { background: #ed5061; }.orderAction.clicked { transform: scale(.97); }
  .finalDetails { margin-top: 18px; line-height: 1.8; }.panel > .balance { margin-top: 18px; }.panel > .balance img { width: 28px; height: 28px; }
  .highlight { outline: 2px solid #459ef3; outline-offset: 2px; }.cursor { position: absolute; left: var(--cursor-x); top: var(--cursor-y); width: 22px; height: 26px; filter: drop-shadow(0 2px 2px #0003); pointer-events: none; }
  @media (max-height: 820px) and (min-width: 761px), (max-width: 760px) { .cifraCard { inset: 14px 26px 94px; }.brand { height: 30px; padding-inline: 10px; }.brand img { width: 18px; height: 18px; }.brand strong { font-size: 12px; }.brand strong span { font-size: 9px; }.brand > small { display: none; }.topUp { margin-left: auto; font-size: 8px; padding: 4px 6px; }.navigation { height: 24px; font-size: 8px; gap: 18px; }.navigation .chosen { padding-block: 5px; }.panel { padding: 9px 12px; }.panelTitle { font-size: 11px; margin-bottom: 8px; }.accountRow { margin-block: 5px; padding: 6px; font-size: 9px; }.accountRow small { font-size: 8px; }.fundingTabs { margin-bottom: 8px; font-size: 8px; }.fundingAsset { padding: 6px; font-size: 10px; }.fundingAsset img { width: 16px; height: 16px; }.fundingDetails { padding-block: 8px; font-size: 10px; gap: 4px; }.fundingDetails > span, .fundingDetails small, .ownDetails { font-size: 8px; }.ownDetails { padding: 6px; }.terminal { padding: 8px; gap: 8px; }.tickerSearch { padding: 5px; font-size: 8px; }.tickerHeading { padding-block: 5px; font-size: 7px; }.tickerRow { font-size: 8px; padding: 5px 3px; }.chart { height: 49px; margin-top: 6px; }.history { padding-block: 5px; margin-top: 6px; font-size: 8px; }.balance { margin-top: 5px; font-size: 9px; }.balance small { font-size: 7px; }.orderPanel { padding: 6px; line-height: 1.25; }.orderPanel > strong { font-size: 8px; }.orderSide { margin-top: 5px; padding: 4px; font-size: 9px; }.orderLabel { margin-top: 5px; font-size: 7px; }.marketType { padding: 4px; font-size: 8px; }.amountTabs { padding-top: 5px; font-size: 7px; }.amountInput { margin-top: 4px; padding: 5px; min-height: 23px; font-size: 8px; }.amountInput small { font-size: 7px; }.orderTotal { display: none; }.orderTotal > span { display: none; }.orderAction { margin-top: 7px; padding: 6px 3px; font-size: 8px; }.cursor { width: 18px; height: 22px; } }
  @media (prefers-reduced-motion: reduce) { .cursor { display: none; } }
</style>
